### ISSUE TITLE
Tooltip for link text and Article Preview Clash

### ISSUE THREAD

**Issue by dqian3** [wikispeedruns/wikipedia-speedruns#298] opened 2022-04-01 06:01 UTC
![image](https://user-images.githubusercontent.com/11544076/161204200-70f821cf-d88a-42f0-b56d-6a8a82851eee.png)

**Comment by maggarwal99** [comment] 2022-04-01 06:13
Duplicate of #294, closing in favor of that instead

**Closed by maggarwal99** 2022-04-01 06:13 UTC
Labels: bug: minor, UI
